export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_PREV_APP_STATE = 'SET_PREV_APP_STATE';
